import { Readex_Pro } from "next/font/google";
import "./globals.css";
import { ActiveSectionProvider, Navbar } from "@/components/Navbar";

const readexPro = Readex_Pro({
  variable: "--font-readex-pro",
  subsets: ["latin", "arabic"],
  display: "swap",
});

export const metadata = {
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      // Optional: Add fallback for older browsers
      { url: '/favicon.png', type: 'image/png' },
    ],
  },
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${readexPro.variable} readex_pro antialiased bg-[#F6F5F4] pb-3`}
      >
        <ActiveSectionProvider>
          <Navbar/>
          {children}
        </ActiveSectionProvider>
      </body>
    </html>
  );
}
