import { Readex_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const readexPro = Readex_Pro({
  variable: "--font-readex-pro",
  subsets: ["latin", "arabic"], // add "arabic" if you need Arabic support
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${readexPro.variable} readex_pro antialiased bg-[#F6F5F4] pb-6`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
